version: "3"

services:
  npm:
    image: node
    user: node
    working_dir: /home/node/app
    entrypoint: npm
    volumes:
      - .:/home/node/app

  sh:
    image: alpine
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
